config/routes.rb
Rails.application.routes.draw do
  root 'rps_game#index'
  get 'result/:id', to: 'rps_game#result', as: 'result_rps'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
end

app/controllers/rps_game_controller.rb
class RpsGameController < ApplicationController
  def index
  end

  def result
    @user_choice = params[:id]
    game_service = RpsGameService::Main.new(user_bet: @user_choice)
    @server_choice = game_service.generated_bet
    @result = game_service.result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RockPaperScissors</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rps_game/index.html.erb
<div class="game-container">
  <h1> ROCK – PAPER – SCISSORS </h1>

  <p class="game-description">
    Rock Paper Scissors is a zero sum game that is usually played by two people using their hands and no tools.
    The idea is to make shapes with an outstretched hand where each shape will have a certain degree
    of power and will lead to an outcome. In addition, hammer is added.
    Hammer is a variation of rock that can beat both scissors and paper, but loses to rock.
  </p>

  <p class="bet-selection"> CHOOSE YOUR MOVE </p>

  <div class="options-container">
    <%= link_to result_rps_path(id: 'rock'), class: 'option-link' do %>
      <%= image_tag('rock.svg', class: 'option-image') %>
      <div class="option-label">Rock</div>
    <% end %>

    <%= link_to result_rps_path(id: 'paper'), class: 'option-link' do %>
      <%= image_tag('paper.svg', class: 'option-image') %>
      <div class="option-label">Paper</div>
    <% end %>

    <%= link_to result_rps_path(id: 'scissors'), class: 'option-link' do %>
      <%= image_tag('scissors.svg', class: 'option-image') %>
      <div class="option-label">Scissors</div>
    <% end %>

    <%= link_to result_rps_path(id: 'hammer'), class: 'option-link' do %>
      <%= image_tag('hammer.svg', class: 'option-image') %>
      <div class="option-label">Hammer</div>
    <% end %>
  </div>
</div>

app/views/rps_game/result.html.erb
<div class="result-screen">
  <h1>RESULT OF THE GAME</h1>

  <div class="result-container">
    <div class="result-box">
      <%= image_tag("#{@user_choice}.svg", class: 'result-image') %>
      <p>Your choice</p>
    </div>

    <div class="result-box">
      <%= image_tag("#{@server_choice}.svg", class: 'result-image') %>
      <p>Server's choice</p>
    </div>
  </div>

  <div class="outcome-message">
    <% if @result == :user %>
      <p>Congratulations! You won!</p>
    <% elsif @result == :server %>
      <p>Sorry! You lost!</p>
    <% else %>
      <p>It's a tie!</p>
    <% end %>
  </div>

  <div class="retry-button">
    <%= link_to 'Play Again', root_path, class: 'button-link' %>
  </div>
</div>